### PR TITLE
DRMAAV2-12 : Skeleton directory structure and Support for Autotools 

### PR DESCRIPTION
**Pull request by vinodchitrali**
#### Issue-ID

* **[DRMAAV2-12](https://pbspro.atlassian.net/browse/DRMAAV2-12)**

#### Problem description
* Skeleton directory structure and Support for Autotools 

#### Cause / Analysis
* None 

#### Solution description
* Initial autotools infrastructure. Some important m4 macros. 

#### Checklist:

- [x] I have joined the **[pbspro community forum](http://community.pbspro.org/)**.
- [x] My pull request contains a **single, signed** commit. See **[setting up gpg signature](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)**.
- [x] My code follows the **[coding style](https://pbspro.atlassian.net/wiki/display/DG/Coding+Standards)** of this project.
- [ ] My change requires project documentation. See **[required documentation checklist](https://pbspro.atlassian.net/wiki/display/DG/Checklist+for+Developing+Features+and+Bug+Fixes)** for details.
- [ ] I have added documentation in the **[project documentation area](https://pbspro.atlassian.net/wiki/display/PD)**.
- [ ] I have added new **unit test(s) to my commit**. *(or)*
- [ ] I have added  **manual test(s) to the Jira ticket and explained why unit testing is not appropriate** for this case.
- [ ] All new and existing automated tests have passed. 
- [ ] I have attached **test logs to the Jira ticket** as evidence of testing/verification.

__***For further information please visit the [Developer Guide Home](https://pbspro.atlassian.net/wiki/display/DG/Developer+Guide+Home).***__

### CODE REVIEW

**Comment by mike0042** [comment]
Please rebase your branch in preparation for merge.

**Comment by vinodchitrali** [comment]
@mike0042 , PR ready to be merge.

**Comment by subhasisb** [comment]
@mike0042 @vinodchitrali this commit was not signed!

**Comment by subhasisb** [comment]
Please revert this commit and ensure that only signed commits are merged. We will need to be careful till we get the CI running on this repository.

**Comment by mike0042** [comment]
I should have checked before I merged. My mistake. I'll ask that @vinodchitrali revert it. I know @agrawalravi90 has some experience with this.

**Comment by vinodchitrali** [comment]
My mistake. I think i cant rewrite the history on master, only maintainer can do that. Have asked @subhasisb to rewrite the history with signed commit

**Comment by bhroam** [comment]
If I'm not mistaken, you'll have to do a git reset and a force push.  Only Subhasis can do a force push to master.  He's the repo owner.

**Comment by agrawalravi90** [comment]
since it is the latest commit on the branch, it's more straight-forward. This should solve it:
Vinod:
- do a git commit --amend -S and sign your commit.
- do a git push -f <your private fork> to force push the signed commit to your fork

Subhasis:
- do a git reset --hard HEAD~1 to reset your local copy of master back to before this was merged
- do a git pull <url to vinod's private fork> <his updated branch>, this should merge in Vinod's signed commit, should be a fast forward commit.
- do a git push -f private_golden master to force push it to master

**Comment by vinodchitrali** [comment]
@agrawalravi90, I my branch i have pushed the signed commit

**Comment by agrawalravi90** [comment]
Hey Vinod,

I see that you have only a master branch in your fork. And that seems to have one extra commit (for DRMAAV2-18) after DRMAAV2-12 (which is still unsigned). This is why it's recommended to do development in separate development branches.

I suggest that you create a dev branch (let's call it 'backup' for now) from your master and reset your master to the golden repository:
(assuming you call your golden repository remote 'private_golden')
git checkout -b backup master
git checkout master
git fetch private_golden/master
git reset --hard private_golden/master

Then sign the commit and push to your fork:
(assuming that you call your fork 'private_fork')
git commit --amend -S
git push -f private_fork master

(at this point Subhasis should be able to take it forward from his side)

After this, you will have to fix your dev branch. You can do this as:
do a "git log" on 'backup' and copy the commit hash of the commit for DRMAAV2-18
git checkout -b DRMAAV2-18 master
git cherry-pick <commit hash that you copied>

Once you are sure that everything is fine, you can delete 'backup': git branch -d backup

Please let me know if you have any questions.

**Comment by vinodchitrali** [comment]
Thanks @agrawalravi90

pushed singed commit to https://github.com/vinodchitrali/DRMAAv2/commits/master  

@subhasisb can you cherry pick the commit

**Pull request merged**
